[package]
name = "elap-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "elap-desktop"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
elap-core = { path = "../elap-core" }

[dev-dependencies]
