# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\nelap.agent\"6\n\x13\x45xecuteAgentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"i\n\x14\x45xecuteAgentResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x10\n\x08progress\x18\x04 \x01(\x02\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"g\n\x11\x45xecuteAgentChunk\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05\x63hunk\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x02\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\x90\x02\n\x10\x41IRuntimeService\x12Q\n\x0c\x45xecuteAgent\x12\x1f.elap.agent.ExecuteAgentRequest\x1a .elap.agent.ExecuteAgentResponse\x12Y\n\x15\x45xecuteAgentStreaming\x12\x1f.elap.agent.ExecuteAgentRequest\x1a\x1d.elap.agent.ExecuteAgentChunk0\x01\x12N\n\x0bHealthCheck\x12\x1e.elap.agent.HealthCheckRequest\x1a\x1f.elap.agent.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEAGENTREQUEST']._serialized_start=27
  _globals['_EXECUTEAGENTREQUEST']._serialized_end=81
  _globals['_EXECUTEAGENTRESPONSE']._serialized_start=83
  _globals['_EXECUTEAGENTRESPONSE']._serialized_end=188
  _globals['_HEALTHCHECKREQUEST']._serialized_start=190
  _globals['_HEALTHCHECKREQUEST']._serialized_end=227
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=229
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=283
  _globals['_EXECUTEAGENTCHUNK']._serialized_start=285
  _globals['_EXECUTEAGENTCHUNK']._serialized_end=388
  _globals['_AIRUNTIMESERVICE']._serialized_start=391
  _globals['_AIRUNTIMESERVICE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
