# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIRuntimeServiceStub:
    """Servicio principal del AI Runtime
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAgent = channel.unary_unary(
                '/elap.agent.AIRuntimeService/ExecuteAgent',
                request_serializer=agent__pb2.ExecuteAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.ExecuteAgentResponse.FromString,
                _registered_method=True)
        self.ExecuteAgentStreaming = channel.unary_stream(
                '/elap.agent.AIRuntimeService/ExecuteAgentStreaming',
                request_serializer=agent__pb2.ExecuteAgentRequest.SerializeToString,
                response_deserializer=agent__pb2.ExecuteAgentChunk.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/elap.agent.AIRuntimeService/HealthCheck',
                request_serializer=agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.SearchDocuments = channel.unary_unary(
                '/elap.agent.AIRuntimeService/SearchDocuments',
                request_serializer=agent__pb2.SearchDocumentsRequest.SerializeToString,
                response_deserializer=agent__pb2.SearchDocumentsResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/elap.agent.AIRuntimeService/GenerateReport',
                request_serializer=agent__pb2.GenerateReportRequest.SerializeToString,
                response_deserializer=agent__pb2.GenerateReportResponse.FromString,
                _registered_method=True)
        self.ExecuteAgentWithRAG = channel.unary_unary(
                '/elap.agent.AIRuntimeService/ExecuteAgentWithRAG',
                request_serializer=agent__pb2.ExecuteAgentWithRAGRequest.SerializeToString,
                response_deserializer=agent__pb2.ExecuteAgentWithRAGResponse.FromString,
                _registered_method=True)


class AIRuntimeServiceServicer:
    """Servicio principal del AI Runtime
    """

    def ExecuteAgent(self, request, context):
        """Ejecutar un agente (respuesta completa)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAgentStreaming(self, request, context):
        """Ejecutar un agente con streaming (tokens en vivo)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocuments(self, request, context):
        """=== NUEVOS RPC PARA FASE 2 ===

        Buscar documentos en RAG
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """Generar reporte (PDF/Excel)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAgentWithRAG(self, request, context):
        """Ejecutar agente con contexto RAG
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAgent,
                    request_deserializer=agent__pb2.ExecuteAgentRequest.FromString,
                    response_serializer=agent__pb2.ExecuteAgentResponse.SerializeToString,
            ),
            'ExecuteAgentStreaming': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteAgentStreaming,
                    request_deserializer=agent__pb2.ExecuteAgentRequest.FromString,
                    response_serializer=agent__pb2.ExecuteAgentChunk.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent__pb2.HealthCheckResponse.SerializeToString,
            ),
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=agent__pb2.SearchDocumentsRequest.FromString,
                    response_serializer=agent__pb2.SearchDocumentsResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=agent__pb2.GenerateReportRequest.FromString,
                    response_serializer=agent__pb2.GenerateReportResponse.SerializeToString,
            ),
            'ExecuteAgentWithRAG': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAgentWithRAG,
                    request_deserializer=agent__pb2.ExecuteAgentWithRAGRequest.FromString,
                    response_serializer=agent__pb2.ExecuteAgentWithRAGResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elap.agent.AIRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('elap.agent.AIRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIRuntimeService:
    """Servicio principal del AI Runtime
    """

    @staticmethod
    def ExecuteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elap.agent.AIRuntimeService/ExecuteAgent',
            agent__pb2.ExecuteAgentRequest.SerializeToString,
            agent__pb2.ExecuteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAgentStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/elap.agent.AIRuntimeService/ExecuteAgentStreaming',
            agent__pb2.ExecuteAgentRequest.SerializeToString,
            agent__pb2.ExecuteAgentChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elap.agent.AIRuntimeService/HealthCheck',
            agent__pb2.HealthCheckRequest.SerializeToString,
            agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elap.agent.AIRuntimeService/SearchDocuments',
            agent__pb2.SearchDocumentsRequest.SerializeToString,
            agent__pb2.SearchDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elap.agent.AIRuntimeService/GenerateReport',
            agent__pb2.GenerateReportRequest.SerializeToString,
            agent__pb2.GenerateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAgentWithRAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elap.agent.AIRuntimeService/ExecuteAgentWithRAG',
            agent__pb2.ExecuteAgentWithRAGRequest.SerializeToString,
            agent__pb2.ExecuteAgentWithRAGResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
